version: '3.1'
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - ./.dbData:/data/db
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - skynet
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./.dbData:/data/db
    networks:
      - skynet
  app:
    # need to pull image from dockerhub
    # image:
    networks:
      - stonknet
    ports:
      - '4500:4500'

volumes:
  # This is for the docker-sync container that gets started
  stonks_app-sync:
    external: true

networks:
  skynet:
