version: '3.1'
services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - ./.dbData:/data/db
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - skynet
  db:
    container_name: mongodb
    image: mongo:latest
    restart: always
    volumes:
      - ./.dbData:/data/db
    networks:
      - skynet
  app:
    # need to pull image from dockerhub
    container_name: app
    image: rooiss/stonks:latest
    env_file: ../../.env
    networks:
      - skynet
    ports:
      - '4500:4500'

networks:
  skynet:
